# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_approval_reconciler.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n client_approval_reconciler.proto\x12*goosechase.data.client_approval_reconciler\"f\n\x1f\x43lientApprovalReconcilerRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\x12\x15\n\rtagger_output\x18\x02 \x01(\t\x12\x17\n\x0f\x63lient_feedback\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_approval_reconciler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTAPPROVALRECONCILERREQUEST']._serialized_start=80
  _globals['_CLIENTAPPROVALRECONCILERREQUEST']._serialized_end=182
# @@protoc_insertion_point(module_scope)
